from src.PriorityQueue.priority_queue import PriorityQueue

if __name__ == '__main__':
    heap = PriorityQueue(comparator=lambda x, y: x > y)
    heap.add(7)
    heap.add(3)
    heap.add(7)
    heap.add(2)
    heap.add(6)
    print(heap.items)
    print(heap.extract())
    print(heap.extract())
    print(heap.extract())
    print(heap.extract())
    print(heap.extract())
    print(heap.items)
    heap2 = PriorityQueue(items=[7, 3, 7, 2, 6], comparator=lambda x, y: x > y)
    print(heap2.items)
    print(heap2.extract())
    print(heap2.extract())
    print(heap2.extract())
    print(heap2.extract())
    print(heap2.extract())
    print(heap2.items)